/**
 * tailwind-styled-v4 — Embedded Tailwind Engine
 *
 * Compiler menjalankan Tailwind internally — tidak perlu tailwind CLI,
 * tidak perlu postcss config manual.
 *
 * Cara kerja:
 * 1. Compiler extract semua class dari source (via classExtractor)
 * 2. Engine generate CSS hanya untuk class tersebut
 * 3. CSS di-output per route (route-level CSS bundling)
 *
 * Ini membuat CSS output jauh lebih kecil:
 *   Tailwind normal: ~300kb global
 *   Route CSS:       ~2–10kb per route
 *
 * NOTE: v5 only supports Tailwind v4. v3 support has been removed.
 */

import path from "node:path"
import { loadTailwindConfig } from "./loadTailwindConfig"
import { getAllRoutes, getRouteClasses } from "./routeCssCollector"

export type TailwindEngineMode = "jit" | "build" | "manual"

export interface TailwindEngineOptions {
  mode?: TailwindEngineMode
  cwd?: string
  outputDir?: string
  config?: Record<string, any>
  minify?: boolean
}

export interface CssGenerateResult {
  route: string
  css: string
  classes: string[]
  sizeBytes: number
}

// ─────────────────────────────────────────────────────────────────────────────
// Core engine
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Try to use Tailwind's internal API for CSS generation.
 * Fallback ke manual CSS generation jika Tailwind API tidak tersedia.
 *
 * NOTE: v5 only supports Tailwind v4. v3 support has been removed.
 */
export async function generateCssForClasses(
  classes: string[],
  config?: Record<string, any>,
  cwd = process.cwd()
): Promise<string> {
  // ── Strategy 0: Rust compile_css (FASTEST — always available) ───────────
  // 200+ Tailwind class mappings, full color palette, arbitrary values
  try {
    const { compileCssFromClasses } = require("./cssCompiler") as typeof import("./cssCompiler")
    const result = compileCssFromClasses(classes)
    if (result?.css && result.resolvedClasses.length > 0) {
      // Jika Rust bisa resolve >50% kelas, pakai hasilnya
      const resolveRate = result.resolvedClasses.length / classes.length
      if (resolveRate >= 0.5) return result.css
    }
  } catch {
    /* fallback ke PostCSS */
  }

  const twConfig = config ?? loadTailwindConfig(cwd)

  // Strategy 1: Tailwind v4 (@tailwindcss/postcss atau native)
  try {
    return await generateViaTailwindV4(classes, twConfig, cwd)
  } catch {
    // not available
  }

  // Strategy 2: Manual atomic CSS generation (always available)
  return generateManualCss(classes)
}

/**
 * Tailwind v4 CSS generation (via @tailwindcss/postcss)
 */
async function generateViaTailwindV4(
  classes: string[],
  _config: Record<string, any>,
  cwd: string
): Promise<string> {
  // Tailwind v4 uses @import "tailwindcss" syntax
  // We generate a virtual CSS file that imports tailwindcss + safelist
  const virtualCss = [
    `@import "tailwindcss";`,
    `@layer utilities {`,
    `  /* Generated by tailwind-styled-v4 */`,
    `}`,
  ].join("\n")

  const postcss = require("postcss")
  const tailwindcss = require("@tailwindcss/postcss")

  const result = await postcss([
    tailwindcss({
      optimize: { minify: false },
    }),
  ]).process(virtualCss, {
    from: path.join(cwd, "virtual.css"),
  })

  // Filter to only include classes we need
  return filterCssForClasses(result.css, classes)
}

/**
 * @deprecated in v5 — Tailwind v3 is no longer supported
 * This function will be removed in v6
 * Use @tailwind-styled/atomic or Tailwind v4 instead
 */
async function generateViaTailwindV3(
  classes: string[],
  config: Record<string, any>
): Promise<string> {
  const postcss = require("postcss")
  const tailwindcss = require("tailwindcss")

  // Create virtual content with only our classes
  const virtualContent = classes.map((c) => `<div class="${c}">`).join("\n")

  const twConfigWithContent = {
    ...config,
    content: [{ raw: virtualContent, extension: "html" }],
    safelist: classes,
  }

  const inputCss = `@tailwind base;\n@tailwind components;\n@tailwind utilities;`

  const result = await postcss([tailwindcss(twConfigWithContent)]).process(inputCss, {
    from: undefined,
  })

  return result.css
}

/**
 * Manual atomic CSS generation — always available, no Tailwind dependency.
 * Menggunakan AtomicCss module yang sudah ada.
 */
function generateManualCss(classes: string[]): string {
  const { generateAtomicCss, parseAtomicClass } = require("./atomicCss")

  const rules = classes.map((c: string) => parseAtomicClass(c)).filter(Boolean)

  if (rules.length === 0) return ""

  const header = `/* Generated by tailwind-styled-v4 — ${new Date().toISOString()} */\n`
  return header + generateAtomicCss(rules)
}

/**
 * Filter compiled Tailwind CSS to only include needed class selectors.
 * Dipakai untuk optimize output CSS size.
 */
function filterCssForClasses(fullCss: string, classes: string[]): string {
  // Keep @base rules + only selectors matching our classes
  const _classSet = new Set(classes)

  const lines = fullCss.split("\n")
  const kept: string[] = []
  let inBlock = false
  let keepBlock = false
  let braceDepth = 0

  for (const line of lines) {
    // Always keep @layer base (reset styles)
    if (line.includes("@layer base") || line.includes("*, *::before")) {
      kept.push(line)
      continue
    }

    // Check if line is a selector for one of our classes
    if (!inBlock) {
      const isOurClass = classes.some((cls) => {
        const escaped = cls.replace(/[:/[\].!%]/g, "\\$&")
        return line.includes(`.${escaped}`) || line.includes(`.${cls}`)
      })

      if (isOurClass) {
        keepBlock = true
        inBlock = true
        braceDepth = 0
      }
    }

    if (inBlock) {
      if (keepBlock) kept.push(line)
      if (line.includes("{")) braceDepth++
      if (line.includes("}")) {
        braceDepth--
        if (braceDepth <= 0) {
          inBlock = false
          keepBlock = false
        }
      }
    }
  }

  return kept.join("\n")
}

// ─────────────────────────────────────────────────────────────────────────────
// Build-time CSS generation (dipakai di withTailwindStyled buildEnd hook)
// ─────────────────────────────────────────────────────────────────────────────

export async function generateAllRouteCss(
  opts: TailwindEngineOptions = {}
): Promise<CssGenerateResult[]> {
  const { cwd = process.cwd(), outputDir, config, minify = true } = opts

  const results: CssGenerateResult[] = []
  const routes = getAllRoutes()
  const twConfig = config ?? loadTailwindConfig(cwd)

  for (const route of routes) {
    const classes = Array.from(getRouteClasses(route))
    if (classes.length === 0) continue

    try {
      let css = await generateCssForClasses(classes, twConfig, cwd)

      if (minify) {
        css = minifyCss(css)
      }

      results.push({
        route,
        css,
        classes,
        sizeBytes: Buffer.byteLength(css, "utf8"),
      })
    } catch (e) {
      console.warn(`[tailwind-styled-v4] CSS generation failed for route ${route}:`, e)
    }
  }

  // Emit CSS files if outputDir provided
  if (outputDir) {
    const fs = require("node:fs")
    fs.mkdirSync(outputDir, { recursive: true })

    for (const result of results) {
      const filename = routeToFilename(result.route)
      const filepath = path.join(outputDir, filename)
      fs.mkdirSync(path.dirname(filepath), { recursive: true })
      fs.writeFileSync(filepath, result.css)
    }

    const totalSize = results.reduce((sum, r) => sum + r.sizeBytes, 0)
    console.log(
      `[tailwind-styled-v4] Route CSS generated: ${results.length} routes, ${formatBytes(totalSize)} total`
    )
  }

  return results
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function routeToFilename(route: string): string {
  if (route === "/") return "index.css"
  if (route === "__global") return "_global.css"
  return `${route.replace(/^\//, "").replace(/\//g, "_")}.css`
}

function minifyCss(css: string): string {
  return css
    .replace(/\/\*[^*]*\*+([^/*][^*]*\*+)*\//g, "") // remove comments
    .replace(/\s+/g, " ") // collapse whitespace
    .replace(/\s*{\s*/g, "{")
    .replace(/\s*}\s*/g, "}")
    .replace(/\s*:\s*/g, ":")
    .replace(/\s*;\s*/g, ";")
    .trim()
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`
  return `${(bytes / 1024 / 1024).toFixed(1)}MB`
}
