/**
 * @tailwind-styled/runtime
 *
 * Lightweight runtime helpers that consume the metadata JSON produced by the
 * Rust compiler engine. The heavy lifting (class extraction, scoping,
 * CSS generation) happens at build time; this file only:
 *
 *   1. Attaches subcomponent properties to the base React component.
 *   2. Handles conditional class props at runtime (e.g. fullWidth, variant).
 *   3. Stays minimal — no parsing, no CSS-in-JS, no external deps.
 *
 * The plugin bundler (Next.js / Vite / Rspack) automatically rewrites:
 *
 *   const Button = tw.button`bg-blue-500  icon { mr-2 w-5 h-5 }`
 *
 * into:
 *
 *   import { createComponent } from "@tailwind-styled/runtime"
 *   export const Button = createComponent("button", "Button_abc123", {
 *     icon: { tag: "span", class: "Button_icon_abc123" },
 *   })
 *
 * Users never call createComponent directly — it is injected by the compiler.
 */

import React from "react"
export type { LiveTokenSet, TokenMap, TokenSubscriber } from "./liveTokenEngine"
export {
  applyTokenSet,
  createUseTokens,
  generateTokenCssString,
  getToken,
  getTokens,
  liveToken,
  liveTokenEngine,
  setToken,
  setTokens,
  subscribeTokens,
  tokenRef,
  tokenVar,
} from "./liveTokenEngine"

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

export interface SubComponentDef {
  /** HTML tag to render (default: "span") */
  tag?: string
  /** Scoped CSS class generated by Rust, e.g. "Button_icon_abc123" */
  class: string
}

export type SubComponentMap = Record<string, SubComponentDef>

/**
 * Map of prop name → CSS class appended when the prop is truthy.
 * e.g. { fullWidth: "w-full", large: "text-lg px-6 py-3" }
 */
export type ConditionalProps = Record<string, string>

/**
 * A compound styled component: base ForwardRef + attached .SubName properties.
 * The generic params are intentionally loose so callers don't need to repeat them.
 */
export type StyledComponent<S extends SubComponentMap = SubComponentMap> =
  React.ForwardRefExoticComponent<
    React.HTMLAttributes<HTMLElement> & React.RefAttributes<HTMLElement>
  > & {
    [K in keyof S]: React.ForwardRefExoticComponent<
      React.HTMLAttributes<HTMLElement> & React.RefAttributes<HTMLElement>
    >
  }

/** Metadata for one compound component produced by Rust. */
export interface ComponentMetadata {
  component: string
  tag: string
  baseClass: string
  subComponents: SubComponentMap
}

// ─────────────────────────────────────────────────────────────────────────────
// cx — tiny className utility (no external dependency)
// ─────────────────────────────────────────────────────────────────────────────

type ClassInput = string | number | false | null | undefined | ClassInput[]

export function cx(...inputs: ClassInput[]): string {
  const out: string[] = []
  for (const input of inputs) {
    if (!input) continue // filters 0, false, null, undefined, ""
    if (typeof input === "string") {
      out.push(input)
    } else if (typeof input === "number") {
      out.push(String(input))
    } else if (Array.isArray(input)) {
      const nested = cx(...input)
      if (nested) out.push(nested)
    }
  }
  return out.join(" ")
}

// ─────────────────────────────────────────────────────────────────────────────
// createComponent
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build a compound styled React component from Rust-generated metadata.
 *
 * @param tag           HTML element tag, e.g. "button" | "div"
 * @param baseClass     Scoped base class from Rust, e.g. "Button_abc123"
 * @param subComponents Map of subcomponent definitions (optional)
 * @param conditionals  Map of prop name → CSS class (optional)
 *
 * @example
 * // Injected automatically by the compiler — do not call manually
 * const Button = createComponent("button", "Button_abc123", {
 *   icon: { tag: "span", class: "Button_icon_abc123" },
 *   text: { tag: "span", class: "Button_text_abc123" },
 * }, { fullWidth: "w-full" })
 *
 * // Usage in JSX:
 * <Button fullWidth>
 *   <Button.icon>🔍</Button.icon>
 *   <Button.text>Search</Button.text>
 * </Button>
 */
export function createComponent<S extends SubComponentMap = SubComponentMap>(
  tag: string,
  baseClass: string,
  subComponents?: S,
  conditionals?: ConditionalProps
): StyledComponent<S> {
  type Props = React.HTMLAttributes<HTMLElement> &
    React.RefAttributes<HTMLElement> &
    Record<string, unknown>

  // ── Base component ─────────────────────────────────────────────────────────
  const Base = React.forwardRef<HTMLElement, Props>(function TwBase(props, ref) {
    const extra: string[] = []

    // Collect conditional classes
    if (conditionals) {
      for (const [prop, cls] of Object.entries(conditionals)) {
        if (props[prop]) extra.push(cls)
      }
    }

    // Build clean props — strip conditional + subcomponent boolean props
    const clean: Record<string, unknown> = {}
    const stripKeys = new Set([
      "className",
      ...(conditionals ? Object.keys(conditionals) : []),
      ...(subComponents ? Object.keys(subComponents) : []),
    ])
    for (const [k, v] of Object.entries(props)) {
      if (!stripKeys.has(k)) clean[k] = v
    }

    const className = cx(baseClass, ...extra, (props.className as string) ?? "")

    return React.createElement(tag, { ...clean, ref, className: className || undefined })
  })

  ;(Base as { displayName?: string }).displayName = "tw." + String(tag)

  // ── Attach subcomponent properties ────────────────────────────────────────
  if (subComponents) {
    for (const [subName, def] of Object.entries(subComponents)) {
      const subTag = def.tag ?? "span"
      const subClass = def.class

      const SubComp = React.forwardRef<HTMLElement, Props>(function TwSub(props, ref) {
        const className = cx(subClass, (props.className as string) ?? "")
        const clean: Record<string, unknown> = { ...props }
        delete clean.className
        return React.createElement(subTag, { ...clean, ref, className: className || undefined })
      })

      ;(SubComp as { displayName?: string }).displayName =
        "tw." + String(tag) + "." + String(subName)

      ;(Base as unknown as Record<string, unknown>)[subName] = SubComp
    }
  }

  return Base as unknown as StyledComponent<S>
}
